<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos [ 
 <!ELEMENT productos (producto)*>
<!ELEMENT producto (identificacion, nombre)>
<!ELEMENT identificacion (codigo | id)*>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)> 
]>

<!-- Ejercicio 8:
El siguiente documento XML ("productos.xml") está bien formado. Sin embargo, no es válido.
Para que lo  sea, realizar los cambios necesarios en dicho documento, pero sin modificar la DTD interna. 
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE productos [ 
 <!ELEMENT productos (producto)*> 
 <!ELEMENT producto (identificacion, nombre)> 
 <!ELEMENT identificacion (#PCDATA | codigo | id)*> 
 <!ELEMENT codigo (#PCDATA)> 
 <!ELEMENT id (#PCDATA)> 
 <!ELEMENT nombre (#PCDATA)> 
]> 
<productos> 
 <nombre>martillo</nombre> 
 <identificacion> 
 Quedan 14 unidades. 
 <codigo>MAR264</codigo> 
 </identificacion> 
 <identificacion> 
 <codigo>DES387</codigo> 
 <id>678984</id> 
 No hay stock. 
 <nombre>destornillador</nombre> 
 </identificacion> 
</productos>-->


<productos>
    <producto>
        <nombre>martillo</nombre>
        <identificacion>
            <codigo>MAR264</codigo>
        </identificacion>
    </producto>
    <producto>
        <nombre>destornillador</nombre>
        <identificacion>
            <codigo>DES387</codigo>
            <id>678984</id>
        </identificacion>
    </producto>
</productos>