<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciudades [ 
 <!ELEMENT ciudades (ciudad+)>
<!ELEMENT ciudad (nombre, capital)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT capital EMPTY> 
]>

<!-- Ejercicio 11:

El siguiente documento XML ("ciudades.xml") está bien formado. Sin embargo, no es válido. Para que lo  sea, realizar los cambios necesarios en la DTD interna de dicho documento. 
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE ciudades [ 
 <!ELEMENT ciudades (ciudad)> 
 <!ELEMENT ciudad (nombre, capital)> 
 <!ELEMENT nombre (#PCDATA)> 
 <!ELEMENT capital EMPTY> 
]> 
<ciudades> 
 <ciudad> 
 <nombre>Buenos Aires</nombre> 
 <capital/> 
 </ciudad> 
 <ciudad> 
 <nombre>Liverpool</nombre> 
 </ciudad> 
 <ciudad> 
 <nombre>Osaka</nombre> 
 </ciudad> 
 <ciudad> 
 <nombre>Oslo</nombre> 
 <capital/> 
 </ciudad> 
</ciudades>-->

<ciudades>
    <ciudad>
        <nombre>Buenos Aires</nombre>
        <capital/>
    </ciudad>
    <ciudad>
        <nombre>Liverpool</nombre>
        <capital></capital>
    </ciudad>
    <ciudad>
        <nombre>Osaka</nombre>
        <capital></capital>
    </ciudad>
    <ciudad>
        <nombre>Oslo</nombre>
        <capital/>
    </ciudad>
</ciudades>